server.port=8080
spring.application.name=gateway-service

# Conexión limpia con tu servidor Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Desactivamos el buscador automático conflictivo de Spring Boot 3.4
spring.cloud.gateway.discovery.locator.enabled=false

# Forzar al Gateway a leer la carpeta static por HTTP
spring.web.resources.static-locations=classpath:/static/