spring.application.name=pasajero_service
server.port=8092

spring.datasource.url=jdbc:mysql://localhost:3306/pasajeros_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.flyway.enabled=true
spring.flyway.clean-disabled=false