server:
  port: 8083

spring:
  application:
    name: vehiculo-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/vehiculo_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    #http://localhost:8083/swagger-ui/index.html para entrar al swagger para testear

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html